# set the python runtime

FROM python:3.11.9-slim

# Container working directory for Docker
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt /app/

# Install any needed package specified in requirement.txt 

RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 8000 available to the world outside the container

EXPOSE  8000

# Define environment variable
ENV PORT=8000

#  Run uvicorn server when the container launches

CMD uvicorn app:app --host 0.0.0.0 --port $PORT


